In [1]:
# Load Dataset

import pandas as pd
import numpy as np

df = pd.read_csv("telecom_customer_churn_feature_engineering.csv")

In [2]:
# Inspect Raw Values

df[["monthly_income", "monthly_bill"]].head()

   monthly_income  monthly_bill
0         57643.0       10049.0
1         18207.0        2752.0
2         13075.0        3155.0
3         38890.0        5859.0
4         17475.0        5106.0

In [4]:
# check why scaling is required

df[["monthly_income", "monthly_bill"]].describe()

       monthly_income  monthly_bill
count     1200.000000   1200.000000
mean     31155.975833   5939.150833
std      19351.937726   4046.473963
min       4984.000000    710.000000
25%      17795.000000   3291.750000
50%      26628.000000   4871.000000
75%      39886.250000   7485.500000
max     209790.000000  36361.000000

In [5]:
# Z-Score Scaling Standardization (Manual)
# 1: Calculate Mean & Std

income_mean = df["monthly_income"].mean()
income_std = df["monthly_income"].std()

print("Mean:", income_mean)
print("Std :", income_std)

Mean: 31155.975833333334
Std : 19351.937725889493

In [6]:
# 2: Apply Z-Score Formula

df["income_zscore"] = (
    df["monthly_income"] - income_mean
) / income_std

df[["monthly_income", "income_zscore"]].head()

   monthly_income  income_zscore
0         57643.0       1.368701
1         18207.0      -0.669131
2         13075.0      -0.934324
3         38890.0       0.399651
4         17475.0      -0.706956

In [7]:
# Verify Z-Score Scaling

df["income_zscore"].mean(), df["income_zscore"].std()

(np.float64(-1.628327102783563e-17), 0.9999999999999997)

In [8]:
# Min-Max Scaling Normalization (Manual)

bill_min = df["monthly_bill"].min()
bill_max = df["monthly_bill"].max()

print("Min:", bill_min)
print("Max:", bill_max)

Min: 710.0
Max: 36361.0

In [9]:
# Apply Min-Max Formula

df["bill_minmax"] = (
    df["monthly_bill"] - bill_min
) / (bill_max - bill_min)

df[["monthly_bill", "bill_minmax"]].head()

   monthly_bill  bill_minmax
0       10049.0     0.261956
1        2752.0     0.057277
2        3155.0     0.068582
3        5859.0     0.144428
4        5106.0     0.123306

In [10]:
# Verify Min-Max Scaling

df["bill_minmax"].min(), df["bill_minmax"].max()

(0.0, 1.0)

In [11]:
# Show minimum, maximum, and a mid value together

df.loc[
    [
        df["monthly_bill"].idxmin(),
        df["monthly_bill"].idxmax(),
        df["monthly_bill"].sort_values().index[len(df)//2]
    ],
    ["monthly_bill", "bill_minmax"]
]

     monthly_bill  bill_minmax
893         710.0     0.000000
968       36361.0     1.000000
47         4873.0     0.116771

In [12]:
# Side-by-Side Comparison

df[[
    "monthly_income",
    "income_zscore",
    "monthly_bill",
    "bill_minmax"
]].head()

   monthly_income  income_zscore  monthly_bill  bill_minmax
0         57643.0       1.368701       10049.0     0.261956
1         18207.0      -0.669131        2752.0     0.057277
2         13075.0      -0.934324        3155.0     0.068582
3         38890.0       0.399651        5859.0     0.144428
4         17475.0      -0.706956        5106.0     0.123306

In [13]:
# Data Leakage — WRONG (Scaling Before Split)

df_scaled_wrong = (
    df["monthly_income"] - df["monthly_income"].mean()
) / df["monthly_income"].std()

df_scaled_wrong.head()

0    1.368701
1   -0.669131
2   -0.934324
3    0.399651
4   -0.706956
Name: monthly_income, dtype: float64